name: Build && publish

on:
  release:
    types:
      - published

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
    
            - name: Setup rye
              uses: eifinger/setup-rye@v3
    
            - name: Install dependencies
              run: |
                rye config --set-bool behavior.use-uv=true
                rye pin 3.11
                rye sync --no-lock
            
            - name: Build
              run: rye build

            - uses: actions/upload-artifact@v3
              with:
                path: ./dist/*
    upload_pypi:
        needs: [build]
        runs-on: ubuntu-latest
        environment: pypi
        permissions:
            id-token: write
        if: github.event_name == 'release' && github.event.action == 'published'

        steps:
        - uses: actions/download-artifact@v3
          with:
        # unpacks default artifact into dist/
        #   if `name: artifact` is omitted, the action will create extra parent dir
            name: artifact
            path: dist

        - uses: pypa/gh-action-pypi-publish@release/v1
          with:
            verbose: true